### ISSUE TITLE
Criteria for removing projects (abandoned ones)?

### ISSUE THREAD

**Issue by mestaritonttu** [davisonio/awesome-irc#14]
I'm thinking about when exactly something stops being awesome :)
Perhaps this is not very relevant for bots, which might become essentially bug-free and "just work" and are easily fixable/extendable. For other IRC software this is more pertinent. The list includes some projects that were left in alpha or beta status years ago (such as TapChat or IRCAnywhere).

**Comment by DanielOaks** [comment]
IRC projects in particular have a decently long shelf-life, and particularly with a couple years of no commits can still somewhat be considered 'active'. I think it's a rough scale of not active code-wise and the maintainers have basically given up on it (e.g. the maintainers of IRCAnywhere tell people to go use The Lounge instead, so that's abandoned).

**Comment by davisonio** [comment]
I think it's something we'll have to look at on an individual basis. Basically I look at commits, bugs, website etc. to see if it's more of a negative to have the item on this list rather than keeping it here. I think it if works, is in use, and is not completely update I'd say keep it.

**Comment by mestaritonttu** [comment]
Thanks for the feedback :)

**Comment by unhammer** [comment]
https://firrre.com/sign-up/ says they've stopped taking sign-ups, and the last tweet on the home page is from 2015 and their twitter account doesn't exist any longer https://twitter.com/ProjectFirrre

**Comment by mestaritonttu** [comment]
Looks like they moved under a different GitHub name and there is very recent activity in https://github.com/FirrreHQ/znc-bootstrap

**Comment by davisonio** [comment]
> [firrre.com/sign-up](https://firrre.com/sign-up/) says they've stopped taking sign-ups, and the last tweet on the home page is from 2015 and their twitter account doesn't exist any longer [twitter.com/ProjectFirrre](https://twitter.com/ProjectFirrre)

I'll remove
